### ISSUE TITLE
Question about free API plan

### ISSUE THREAD

**Issue by nikdaya** [LucasFaudman/linkedin-automator#1]
Hi, does the application require a paid OpenAI plan?

I tried to use the gpt-3.5-turbo model but when the model is prompted for an answer, which doesn't know because I'm starting to use it, I get an exception back saying that I have exceeded the maximum request rate for my plan.

I don't know if this could be caused by me selecting an AI assistant before, which then I removed by deleting the ai.db file and reloading the app again. But even with just an AI model selected with no Agent selected, I keep getting the same rate limit exception.

**Comment by LucasFaudman** [comment]
Hey @nikdaya, 

No, this does not require the paid monthly upgraded OpenAI plan. 

It does however require that billing is enabled on your OpenAI account so that your account can be charged for your API requests. You can do this one of two ways:
- Use the `Add to credit balance` button to add a specific amount
OR 
- Enable auto-charge to pay as you go. 
![image](https://github.com/LucasFaudman/linkedin-ai/assets/52257695/480f767a-a0cf-43e0-b4cc-15e2d406c229)

The link to these settings: https://platform.openai.com/settings/organization/billing/overview

OpenAI has gone back and forth with wether auto-charge is enabled by default, and it looks like the default is disabled again now, so I'll definitely update the README to include the step in the next update.  

Thanks for bringing this to my attention!

**Comment by LucasFaudman** [comment]
Also in case you or anyone reading this is curious: 
- OpenAI does not differentiate between rate limit errors. So using all of your daily token limit for a given model, or using all of your tokens available based on your billing settings will both raise this same error message.
- The Assistant ID and ai.db both would have no effect on this at all. 
- The Assistant ID just specifies which instance to use and can be used to reset the AI's "memory" by selecting a new ID. Or leaving it blank to have one created automatically.
- The ai.db is actually totally optional and is just used for storing AI related data like token usage, tool calls, etc so this data can be referenced later if needed to undstand why the AI made a given decision or to calculate total usage for example.

**Comment by nikdaya** [comment]
Thanks Lucas for the detailed explanation. I see, this makes total sense.

Is there a way to moderate the API expense so that the costs are contained?
I see that you sleep the app for 1 second before checking again for the status of the request, would that value being parametrized reduce the rate of querying the assistant?

If yes, could this value of 1 second (`sleep_interval`) be configurable in the json file?

**Comment by LucasFaudman** [comment]
The best way to contain cost would be to add a small amount to your account and disable auto-recharge. This way the API will stop working (and you'll see the same error message you originally asked about) whenever you run out of tokens. 

[`sleep_interval`](https://github.com/LucasFaudman/linkedin-ai/blob/2ad262ab6804e0bbf9b65abcd1aca9582ae68de5/src/linkedin_ai/jobai.py#L172) actually has no impact on the cost since OpenAI costs are _not_ calculated by number of requests, but by number of tokens used. `sleep_interval` is the amount of time to wait before rechecking the status of a given Run, which does not influence the number of tokens used and thus does not increase cost.

The two factors that increase the number of tokens are:
- The length of your `resume.txt` file since it is included as part of the system prompt for every Run.
- The number and length of questions in your db that contain keywords the AI selected to match a given input question. The more questions that match a given set of keywords, the more tokens used, but the more likely the resulting answer is correct.

In other projects I have used [`tiktoken`](https://cookbook.openai.com/examples/how_to_count_tokens_with_tiktoken) to estimate token usage before submitting requests which will incur token usage, but I have not implemented this here yet since the token usage for is extremely low so I didn't think it was critical yet. 

I've tested it on hundreds of apps and each one only used fractions of a cent so I think you'll find a small amount like $5-10 will take you very far. Hope this helps!

**Comment by nikdaya** [comment]
Thanks a lot Lucas for your answer. Well, given the slight amount of tokens consumed, I think I'll give it a try without too much thinking on performance. Can close this issue and thanks for the suggestion on titkoten (lmao on the name! 🤣)

I have some other questions, though, feel free to ask me to split in other issues:
- Would you consider using AI to assign a rate 0 to 100 regarding the most matching job, given as input to the AI Assistant the title and description of the job along with the skills required, and the resume.txt?
Something like:
```
def evaluate_job(resume, title, description, skills):
    # give to AI resume, title, description, skills
    # prompt is to give 0 - 100 answer
    # save the score into the "score" column of the jobs.db
    # etc...
```

This would allow to not only find jobs and apply but also to apply for the topmost matching jobs, evaluated by AI. In other words, LinkedIn suggestions are not exactly "suggestions", more like an "attempt of suggestion" and it would be great to have an AI estimation on these.

- I noticed the automation going into crisis for two separate situations:
    - When I have a droplist and I have to choose between Yes / No or similar, sometimes selenium keeps tabbing between these without a stop, the only way is to select it manually by pressing "Y" or "N" on the keyboard.
    - When I have a request for the Cover Letter or "message to the hiring manager" I have request for text but it is optional, I would like to be able to skip the optional fields, instead now if I press "OK" the job application is only saved but keeps in state "needs_answer", and if I press "Cancel" I get the same result and state "error".
    
Sorry to bother with all these questions but I feel this repo has great potentiality.

**Comment by LucasFaudman** [comment]
Thanks @nikdaya I appreciate your ideas, definitely not a bother.

I think the job fit evaluation idea is great and I know exactly how to implement this so I've added it to the list of upcoming features. I also just created this discussion thread for adding feature requests so if you have more ideas feel free to add them here: https://github.com/LucasFaudman/linkedin-ai/discussions/2

For the application(s) you are having issue with I just opened this issue for reporting the job ids so I can figure out what's going on and why the particular form type is causing issues. Please report them here and I'll see what's going on: https://github.com/LucasFaudman/linkedin-ai/issues/3

I'm going to close this issue but keep it pinned in case anyone else has the same question. Thanks!
